version: '3.8'

services:
  web:
    build: .
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.host_website_api.rule=Host(`altacee.lol`)"
      - "traefik.http.routers.host_website_api.entrypoints=https"
      - "traefik.http.routers.host_website_api.tls.certresolver=letsencrypt"
      - "traefik.http.services.host_website_api.loadbalancer.server.port=5001"
    volumes:
      - ./room_code_files:/app/room_code_files
    environment:
      - SECRET_KEY=your_secret_key
    networks:
      - traefik-network

  # Optionally, add a file storage service for the code files
  file-storage:
    image: busybox
    volumes:
      - ./room_code_files:/app/room_code_files

networks:
  traefik-network:
    external: true
