version: '3.8'

services:
  web:
    build: .
    volumes:
      - ./room_code_files:/app/room_code_files
    environment:
      - SECRET_KEY=your_secret_key
    networks:
      - traefik-network
    ports:
      - 5001:5001

networks:
  traefik-network:
    external: true
