version: '3.9'

services:
  web:
    build: .
    ports:
      - "5001:5001"
    environment:
      SECRET_KEY: 'your_production_secret_key'
    depends_on:
      - redis
    command: gunicorn -k gevent -w 1 -b 0.0.0.0:5001 app:app

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
